### ISSUE TITLE
Linux deb execution error

### ISSUE THREAD

**Issue by hotrush** [Aluxian/electron-superkit#2]
Trying to build deb package for linux. There was no errors while building and installing. But when i try to run it nothing happens. Than i try to run from terminal executable file, situated at /opt/superkit/superkit and see next error:

```
/opt/superkit $ ./superkit
[14634:0708/175314:ERROR:browser_main_loop.cc(173)] Running without the SUID sandbox! See https://code.google.com/p/chromium/wiki/LinuxSUIDSandboxDevelopment for more information on developing with the sandbox on.
A JavaScript error occured in the browser process
Uncaught Exception:
Error: Cannot find module 'babel-runtime/helpers/interop-require-default'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/opt/superkit/resources/app/scripts/browser/main.js:3:30)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Object.<anonymous> (/opt/superkit/resources/atom.asar/browser/lib/init.js:104:10)
```

Any ideas?

Linux mint 17.1
uname -r 
3.13.0-37-generic

**Comment by hotrush** [comment]
Just missed dependencies for src directory... All working fine. Thanks for an awesome kit!

**Comment by niftylettuce** [comment]
I have the same error, how'd you fix?

**Comment by niftylettuce** [comment]
Nvm, my babel-runtime was a diff version than babel-core required.
