### ISSUE TITLE
Error: Fatal error: Unable to load file

### ISSUE THREAD

**Issue by virushan** [Aluxian/electron-superkit#8]
I followed your tutorial here:
https://github.com/Aluxian/electron-superkit/wiki/Install-Dependencies 
https://github.com/Aluxian/electron-superkit/wiki/Building-&-Watching

unfortunately both build & watch is throwing "Error: Fatal error: Unable to load file"

Here is the exact output:

```
C:\projects\electron-superkit>gulp build:win32
[19:53:06] Requiring external module coffee-script/register
[19:53:08] Using gulpfile C:\projects\electron-superkit\gulpfile.coffee
[19:53:08] Starting 'resources:win'...
[19:53:08] Starting 'kill:win32'...
[19:53:08] Finished 'resources:win' after 27 ms
[19:53:08] Finished 'kill:win32' after 83 ms
[19:53:08] Starting 'download:win32'...
[19:53:08] Verifying requested version (v0.31.1)
[19:53:08] Finished 'download:win32' after 196 ms
[19:53:08] Starting 'clean:build:win32'...
[19:53:08] Finished 'clean:build:win32' after 2.89 ms
[19:53:08] Starting 'compile:win32:menus'...
[19:53:08] Starting 'compile:win32:styles'...
[19:53:08] Starting 'compile:win32:scripts'...
[19:53:08] Starting 'compile:win32:html'...
[19:53:08] Starting 'compile:win32:deps'...
[19:53:08] Starting 'compile:win32:package'...
[19:53:08] Finished 'compile:win32:styles' after 300 ms
[19:53:08] Finished 'compile:win32:package' after 293 ms
[19:53:08] Finished 'compile:win32:html' after 297 ms
[19:53:08] Finished 'compile:win32:menus' after 432 ms
[19:53:08] Finished 'compile:win32:scripts' after 433 ms
[19:53:10] Finished 'compile:win32:deps' after 1.62 s
[19:53:10] Starting 'compile:win32'...
[19:53:10] Finished 'compile:win32' after 3.14 µs
[19:53:10] Starting 'build:win32'...
[19:53:10] 'build:win32' errored after 5.47 ms
[19:53:10] Error: Fatal error: Unable to load file

  at formatError (C:\Users\vmaheswaran\AppData\Roaming\npm\node_modules\gulp\bin
\gulp.js:169:10)
  at Gulp.<anonymous> (C:\Users\vmaheswaran\AppData\Roaming\npm\node_modules\gul
p\bin\gulp.js:195:15)
  at emitOne (events.js:77:13)
  at Gulp.emit (events.js:169:7)
  at Gulp.Orchestrator._emitTaskDone (C:\projects\electron-superkit\node_modules
\orchestrator\index.js:264:8)
  at C:\projects\electron-superkit\node_modules\orchestrator\index.js:275:23
  at finish (C:\projects\electron-superkit\node_modules\orchestrator\lib\runTask
.js:21:8)
  at cb (C:\projects\electron-superkit\node_modules\orchestrator\lib\runTask.js:
29:3)
  at C:\projects\electron-superkit\node_modules\async\lib\async.js:721:13
  at C:\projects\electron-superkit\node_modules\async\lib\async.js:52:16
  at C:\projects\electron-superkit\node_modules\async\lib\async.js:264:21
  at C:\projects\electron-superkit\node_modules\async\lib\async.js:44:16
  at C:\projects\electron-superkit\node_modules\async\lib\async.js:718:17
  at C:\projects\electron-superkit\node_modules\async\lib\async.js:167:37
  at C:\projects\electron-superkit\tasks\utils.coffee:14:5
  at ChildProcess.<anonymous> (C:\projects\electron-superkit\node_modules\rcedit
\lib\rcedit.js:54:16)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:172:7)
  at maybeClose (internal/child_process.js:818:16)
  at Socket.<anonymous> (internal/child_process.js:319:11)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)
```

**Comment by aluxian** [comment]
Could you please paste that log again inside a code block?

(here's how: https://guides.github.com/features/mastering-markdown/ see the `code` example).

I suspect there might be something missing in it.

That error is probably thrown here: https://github.com/Aluxian/electron-superkit/blob/master/tasks/build.coffee#L88

Can you check that file `'./build/win32/electron.exe'` exists? You could also comment out that line, it should still work. However, your exe won't have the correct properties.

**Comment by virushan** [comment]
`'./build/win32/electron.exe'` doesn't exist. I tried `gulp download:win32` executed without any errors however file was not downloaded to directory specified `'outputDir'`. 
https://github.com/Aluxian/electron-superkit/blob/master/tasks/download.coffee#L21

I commeted the code as you mentioned above https://github.com/Aluxian/electron-superkit/blob/master/tasks/build.coffee#L88  which removed the error log but it doesn't build as expected. same issue with `gulp watch:win32`

**Comment by aluxian** [comment]
Can you remove the `build` and `cache` folders and try again?

**Comment by virushan** [comment]
I tried removing both `build` and `cache` folders unfortunately that did not help.

I did couple of testing my self.

tried `gulp download:win32` did not download but this is the log I get:

```
[09:11:39] Requiring external module coffee-script/register
[09:11:41] Using gulpfile c:\projects\aluxian\electron-superkit\gulpfile.coffee
[09:11:41] Starting 'kill:win32'...
[09:11:41] Finished 'kill:win32' after 67 ms
[09:11:41] Starting 'download:win32'...
[09:11:41] Verifying requested version (v0.31.1)

Process finished with exit code 0
```

tried to change the download directory specified in `['win32', 'ia32', 'win32', './build/win32']` https://github.com/Aluxian/electron-superkit/blob/master/tasks/download.coffee#L19
to `['win32', 'ia32', 'win32', './test/win32']`  which did not throw any errors still says successful.

```
[09:17:02] Requiring external module coffee-script/register
[09:17:04] Using gulpfile c:\projects\aluxian\electron-superkit\gulpfile.coffee
[09:17:04] Starting 'kill:win32'...
[09:17:04] Finished 'kill:win32' after 70 ms
[09:17:04] Starting 'download:win32'...
[09:17:04] Verifying requested version (v0.31.1)

Process finished with exit code 0
```

downloaded `electron.exe` manually pasted under `'./build/win32'` build successfully however when I open the build file it doesn't open. I've also noticed resource folder remain unchanged. did not see `.asar` file either  

```
[09:26:40] Requiring external module coffee-script/register
[09:26:42] Using gulpfile C:\projects\electron-superkit\gulpfile.coffee
[09:26:42] Starting 'resources:win'...
[09:26:42] Starting 'kill:win32'...
[09:26:42] Finished 'resources:win' after 24 ms
[09:26:42] Finished 'kill:win32' after 69 ms
[09:26:42] Starting 'download:win32'...
[09:26:42] Verifying requested version (v0.29.0)
[09:26:42] Finished 'download:win32' after 185 ms
[09:26:42] Starting 'clean:build:win32'...
[09:26:42] Finished 'clean:build:win32' after 2.91 ms
[09:26:42] Starting 'compile:win32:menus'...
[09:26:42] Starting 'compile:win32:styles'...
[09:26:42] Starting 'compile:win32:scripts'...
[09:26:42] Starting 'compile:win32:html'...
[09:26:42] Starting 'compile:win32:deps'...
[09:26:42] Starting 'compile:win32:package'...
[09:26:42] Finished 'compile:win32:styles' after 305 ms
[09:26:42] Finished 'compile:win32:html' after 303 ms
[09:26:42] Finished 'compile:win32:package' after 301 ms
[09:26:42] Finished 'compile:win32:menus' after 433 ms
[09:26:42] Finished 'compile:win32:scripts' after 435 ms
[09:26:43] Finished 'compile:win32:deps' after 1.59 s
[09:26:43] Starting 'compile:win32'...
[09:26:43] Finished 'compile:win32' after 3.71 µs
[09:26:43] Starting 'build:win32'...
[09:26:44] Finished 'build:win32' after 160 ms
```

![image](https://cloud.githubusercontent.com/assets/3879856/11746054/f76787a8-9fe9-11e5-9cc9-77ae026cafeb.png)

![image](https://cloud.githubusercontent.com/assets/3879856/11746067/08b99bfe-9fea-11e5-9ca8-0b16bbe3d29a.png)

**Comment by aluxian** [comment]
Does it work if you replace `'./build/win32'` with `'build\win32'`?

I don't know what else to suggest, sorry.

**Comment by pathikdevani** [comment]
check #11
